#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "81"
#endif
#ifndef DETAILED_BUILD_VERSION
  #define DETAILED_BUILD_VERSION "2.1.X.0 build 81 2023-04-28 20:39:52"
#endif
#ifndef SHORT_BUILD_VERSION
  #define SHORT_BUILD_VERSION "2.1.X.0"
#endif
