#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "12"
#endif
#ifndef DETAILED_BUILD_VERSION
  #define DETAILED_BUILD_VERSION "2.1.X.0 build 12 2023-04-10 20:08:45"
#endif
#ifndef SHORT_BUILD_VERSION
  #define SHORT_BUILD_VERSION "2.1.X.0"
#endif
