name: 🪲 Report a bug
description: Create a bug report to help improve Luxuri Firmware
title: "[BUG] (bug summary)"
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Join us on [Discord](https://discord.gg/w8gMzQq8Bp).

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug in Luxuri Firmware!**

        ## Before Reporting a Bug

        - Test with the [`luxmarlin-2.1.x` branch](https://github.com/klack/LuxuriMarlin/archive/luxmarlin-2.1.x.zip) to see whether the issue still exists.

        ## Instructions

        Please follow the instructions below. Failure to do so may result in your issue being closed. See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md) for additional guidelines.

        1. Provide a good title starting with [BUG].
        2. Fill out all sections of this bug report form.
        3. Always attach configuration files so we can build and test your setup.

  - type: dropdown
    attributes:
      label: Did you test the latest `luxmarlin-2.1.x` code?
      description: >-
        Always try the latest code to make sure the issue you are reporting is not already fixed. To download
        the latest code just [click this link](https://github.com/klack/LuxuriMarlin/archive/luxmarlin-2.1.x.zip).
      options:
        - Yes, and the problem still exists.
        - No, but I will test it now!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        When I try to... it doesn't work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.
    validations:
      required: true      

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.
    validations:
      required: true      

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...
      validations:
        required: true        

  - type: input
    attributes:
      label: Version of Luxuri Firmware
      description: Viewable on boot screen.
    validations:
      required: true

  - type: input
    attributes:
      label: Version of Screen Firmware
      description: Viewable on boot screen.
    validations:
      required: true

  - type: input
    attributes:
      label: Machine Configuration
      description: Viewable on boot screen.  i.e. Tenlog D3, 2208 Drivers, BMG Extruder

  - type: dropdown
    attributes:
      label: Your Slicer
      description: Do you use Slic3r, Prusa Slicer, Simplify3D, IdeaMaker...?
      options:
        - Slic3r
        - Simplify3D
        - Prusa Slicer
        - IdeaMaker
        - Cura
        
  - type: dropdown
    attributes:
      label: Host Software
      description: Do you use OctoPrint, Repetier Host, Pronterface...?
      options:
        - SD Card (headless)
        - Repetier Host
        - OctoPrint
        - Pronterface
        - Cura
        - Same as my slicer
        - Other (explain below)

  - type: markdown
    attributes:
      value: |
        # Attachments

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - Log output from the host.  
        - Images or videos demonstrating the problem, if it helps to make it clear.
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
